# Generated by Django 4.1.2 on 2022-10-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intakeapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Misc_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Eating_Out_Delivery', models.SmallIntegerField(default='')),
                ('Auto_Loan_Lease_Payments', models.SmallIntegerField(default='')),
                ('Auto_Gas_Maintenance', models.BigIntegerField(default='')),
                ('Health_Care_Medical_Dental', models.SmallIntegerField(default='')),
                ('Entertainment', models.SmallIntegerField(default='')),
                ('Credit_Cards_Minimum_Payments', models.SmallIntegerField(default='')),
                ('State_Federal_Taxes', models.SmallIntegerField(default='')),
                ('Dependents_Day_Care_Clothing', models.SmallIntegerField(default='')),
                ('Donations', models.SmallIntegerField(default='')),
                ('Education_Tuition_Books', models.SmallIntegerField(default='')),
                ('Pets', models.SmallIntegerField(default='')),
                ('Other_Expenses', models.SmallIntegerField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Auto_Gas_Maintenance',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Auto_Loan_Lease_Payments',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Credit_Cards_Minimum_Payments',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Dependents_Day_Care_Clothing',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Donations',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Education_Tuition_Books',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Entertainment',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Food_Eating_Out_Delivery',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Health_Care_Medical_Dental',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Other_Expenses',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='Pets',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='State_Federal_Taxes',
        ),
    ]
